#! /usr/bin/env bash

#JONATHAN MARQUEZ JIMENEZ
#P22. Haz un script que instale un servidor DHCP.
#  Instalar el servidor, configurar el interfaz, configurar la red, etc.

#CARGAMOS LAS FUNCIONES NECESARIAS PARA EL DHCP
. funciones.sh

#MIRAMOS SI EL USUARIO QUE EJECUTA EL SCRIPT ES ROOT, EN CASO CONTRARIO QUE SALGA
if [[ `whoami` != "root" ]]
then
	echo -e "\x1b[1;31m ERROR:\x1b[0m Este script solo lo puede ejecutar el root."
	exit 1
fi

#MIRAMOS SI EL PAQUETE ESTA INSTALADO
if [[ `which dhcpd` == "" ]]
then
	echo -e "\x1b[1;31m ERROR:\x1b[0m El paquete del dhcp no esta instalado."
	read -p "¿Quieres instalarlo? [Y / n] " insta

	if [[ $insta != "n" && $insta != "N" ]]
	then
		apt update
		apt install isc-dhcp-server figlet
		if [[ $? -eq 1 ]]
		then
			echo -e "\x1b[1;31m ERROR:\x1b[0m NO SE PUDO INTALAR EL PAQUETE isc-dhcp-server"
			read -p "Pulsa intro para salir."
			exit 1
		fi
		clear
	else
		echo -e "\x1b[1;31m ERROR:\x1b[0m NO PUEDES SEGUIR YA QUE SI NO ESTA INSTALADO LOS PAQUETES NECESARIOS NO FUNCIONARA EL SCRIPT"
		read -p "Pulsa intro para salir"
		exit 0
	fi
fi

#BUCLE INFINITO QUE SERA EL MENU
while :
do
	clear
	#MENSAJE DE ENTRADA
	figlet "DHCP"
	echo "#########################################"
	dhcp-lease-list --lease
	echo ""
	#MOSTRAMOS LA TABLA DE LAS IP RESERVADAS
	ip_reservada

	echo ""
	echo "#########################################"
	echo ""
	#MIRAMOS SI EL DHCP FUE CONFIGURADO, CASO CONTRARIO LE DAMOS SOLO LAS OBCIONES DE CONFIGURACION
	if [[ `cat /etc/dhcp/dhcpd.conf | grep -n "#IP RESERVADAS"` == "" ]]
	then
		echo -e "\x1b[1;33mPARA VER LAS DEMAS OBCIONES TENDRAS QUE CONFIGURAR LA TARJETA DE RED EN ESTATICA Y DESPUES CONFIGURAR EL SERVIDOR DHCP\x1b[0m"
		echo ""
		echo "1: Poner interfaz estatica."
		echo "2: Configurar DHCP."
		echo ""
		echo "0: Salir"
	else
		echo "----- CONFIGURAR DHCP ------"
		echo "1: Poner interfaz estatica."
                echo "2: Configurar DHCP."
		echo "----------------------------"
		echo ""
		echo "-------- RESERVA IP --------"
		echo "3: Reservar IP."
		echo "4: Eliminar reserva IP."
		echo "----------------------------"
		echo ""
		echo "--------- LISTAR IP --------"
		echo "5: Listas de equipos ya asignadas DHCP."
		echo "6: IP reservadas."
		echo "----------------------------"
		echo ""
		echo "----- LIMITAR USO DHCP -----"
		echo "7: ON/OFF Limitar uso DHCP."
		echo "8: Añadir equipo."
		echo "9: Eliminar equipo."
		echo "----------------------------"
		echo ""
		echo "0: Salir"
	fi

	read -p "--> " opti

	case $opti in
		0)
			figlet "ADIOS : )"
			exit 0
		;;
		#PONER INTERFAZ ESTATICA
		1)
			clear
			echo "----------------------------------------------"
                        echo "             CONFIGURAR INTERFAZ              "
                        echo "----------------------------------------------"
			ip a
			#PEDIMOS LOS PARAMETRS PARA LA CONFIGURACION
			echo ""
			echo -e "\x1b[1;36m NOTA:\x1b[0m Los campos con * son obligatorios."
			read -p "*Interfaz de red: " inter_server_dhcp
			#MIRAMOS SI LA INTERFAZ EXISTE
			comprobar_interfaz "$inter_server_dhcp"
			#LE PEDIMOS LA IP DEL SERVIDOR Y LOC OMPROBAMOS SI LO PUSO BIEN
			ip_server_dhcp=$(comprobar_ip "*IP del servidor: " "$ip_server_dhcp")
			#IGUAL QUE EL ANTERIOR DE LA IP PERO CON LA MAC
			masc_server_dhcp=$(comprobar_ip "*Mascara: " "$masc_server_dhcp")
			read -p "Dirección de red: " direc_red_server_dhcp
			if [[ $direc_red_server_dhcp != "" ]]; then
				direc_red_server_dhcp=$(comprobar_ip "Dirección de red: " "$direc_red_server_dhcp")
			fi
			read -p "Broadcast: " brod_server_dhcp
			if [[ $brod_server_dhcp != "" ]]; then
                                brod_server_dhcp=$(comprobar_ip "Broadcast: " "$brod_server_dhcp")
                        fi
			read -p "Puerta de enlace: " gate_server_dhcp
			if [[ $gate_server_dhcp != "" ]]; then
                                gate_server_dhcp=$(comprobar_ip "Puerta de enlace: " "$gate_server_dhcp")
                        fi
			read -p "DNS: [EJ: 8.8.8.8] " dns_server_dhcp

			#CAMPOS OBCIONALES
			if [[ "$direc_red_server_dhcp" != "" ]]; then
				direc_red_server_dhcp="network $direc_red_server_dhcp"
			fi
			if [[ "$brod_server_dhcp" != "" ]]; then
				brod_server_dhcp="broadcast $brod_server_dhcp"
			fi
			if [[ "$gate_server_dhcp" != "" ]];then
				gate_server_dhcp="gateway $gate_server_dhcp"
			fi
			if [[ "$dns_server_dhcp" != "" ]];then
				dns_server_dhcp="dns-nameservers $dns_server_dhcp"
			fi

			#MIRAR SI LOS CAMPOS ESTAN LLENOS
			comprobar_campos_vacios "$inter_server_dhcp" "$ip_server_dhcp" "$masc_server_dhcp"

			#MIRAR SI TIENE ALGO REFERENTE A LA INTERFAZ QUE CONFIGURAREMOS DENTRO DEL ARCHIVO
			if [[ `cat /etc/network/interfaces | grep $inter_server_dhcp` != "" ]]
			then
				echo -e "\x1b[1;33m PELIGRO:\x1b[0m Detectamos que el archivo /etc/network/interfaces tiene algo referente a la interfaz $inter_server_dhcp."
				echo "         Si esta configurada ya como -STATIC-, elimine la configuracion para agregar la nueva."
				echo "         Si esta configurada como -DHCP-, elimine la configuracion para agregar la -STATIC-."
				echo "         Si es un tipo de configuracion que no interfiere con la asignacion de -IP STATIC-, ignore este mensaje y siga."
				echo "         Para salir del script pulse Control+c."
				read -p "Pulsa intro para continuar con la configuracion de la interfaz."
			fi

			#AGREGAMOS LOS DATOS ANTERIOR AL ARCHIVO /etc/network/interfaces
			echo "---------------------------------------------"
			echo "Se agregaran los siguientes datos al archivo /etc/network/interfaces"
			echo "---------------------------------------------"
			#MOSTRAMOS EL RESULTADO FINAL
			cat << fin
#INTERFAZ CREADA POR EL SCRIPT DE CONFIGURACION DHCP
auto $inter_server_dhcp
iface $inter_server_dhcp inet static
    address $ip_server_dhcp
    netmask $masc_server_dhcp
    $direc_red_server_dhcp
    $brod_server_dhcp
    $gate_server_dhcp
    $dns_server_dhcp
fin
			echo "---------------------------------------------"
			read -p "¿Estas deacuerdo? [Y / n] " agregar_config
			if [[ $agregar_config != "n" && $agregar_config != "N" ]]
			then
				#REALIZAMOS COPIA DE SEGURIDAD POR SI ACASO
				echo "---------------------------------------------"
				echo "SE REALIZO UNA COPIA DE SEGURIDAD EN /etc/network/interfaces.back"
				echo "---------------------------------------------"

				cp /etc/network/interfaces /etc/network/interfaces.back
				echo -e "
#INTERFAZ CREADA POR EL SCRIPT DE CONFIGURACION DHCP
auto $inter_server_dhcp
iface $inter_server_dhcp inet static
    address $ip_server_dhcp
    netmask $masc_server_dhcp
    $direc_red_server_dhcp
    $brod_server_dhcp
    $gate_server_dhcp
    $dns_server_dhcp
" >> /etc/network/interfaces

				#PARAMOS EL NETWORKING PARA PODER REINICIAR LA INTERFAZ
				echo "Parando el servicio networking, para evitar errores."
				/etc/init.d/networking restart
				#TIRAMOS Y LEVANTAMOS LA INTERFAZ
				ip link set dev $inter_server_dhcp down; ip link set dev $inter_server_dhcp up

				echo "NOTA: Mire si se añadio la IP correctamente, puede que por culpa del networking no se puso la IP correctamente."
				echo "      Para solucionar el problema reinicie el networking y verifique que el archivo interfaces esta todo correcta. Si el problema continua reinicie el servidor."

				echo -e "INTERFAZ $inter_server_dhcp CONFIGURADA [\x1b[1;32m OK \x1b[0m]"
				read -p "Pulsa intro para ir al menu."
			else
				echo -e "\x1b[1;33m NO SE AGREGO LA CONFIGURACION \x1b[0m"
				read -p "Pulsa intro para ir al menu."
			fi
		;;
		#CONFIGURAR DHCP
		2)
			clear
			#REALIZAMOS UNA COPIA DE LA CONFIGURACION QUE TIENE POR DEFECTO
			if [[ `cat /etc/dhcp/dhcpd.conf | grep '# dhcpd.conf'` != "" ]]
			then
			        echo "SE REALIZARA UNA COPIA DEL ARCHIVO /etc/dhcp/dhcpd.conf EN EL MISMO DIRECTORIO"
			        cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.back
			fi

			echo "----------------------------------------------"
			echo "                  DHCP CONFI                  "
			echo "----------------------------------------------"

			echo -e "\x1b[1;36m NOTA:\x1b[0m Eliminaras la configuracion anterior y se añadira esta nueva configuracion."
			echo "      Los campos con * son campos oblogatorios."

			#EMPEZAMOS CON LA CONFIGURACION DEL DHCP
			#LE PEDIMOS EL TIEMPO Y COMPROBAMOS QUE ES UN NUMERO, EN CASO DE QUE NO SEA UN NUMERO SE LO PEDIMOS DE NUEVO
			tiempo_concesion=$(comprobar_variable_numerica "*Tiempo de concesion: [600] " "$tiempo_concesion")
			tiempo_maximo_concesion=$(comprobar_variable_numerica "*Tiempo maximo de concesion: [7200] " "$tiempo_maximo_concesion")
			#LE PEDIMOS LA SUBNET Y LO COMPROBAMOS
			subnet=$(comprobar_ip "*Subnet: [10.0.0.0] " "$subnet")
			#LE PEDIMOS LA MAC Y LO COMPROBAMOS
			masc_subnet=$(comprobar_ip "*Mascara de la subnet: [255.255.255.0] " "$masc_subnet")
			read -p "*Rango de IP para los clientes: [10.0.0.5 10.0.0.50] " ramgo_ip
			#MIRAR SI PUSO EL RANGO
			while [[ `echo "$ramgo_ip" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3} ([0-9]{1,3}\.){3}[0-9]{1,3}\b"` == "" ]]
			do
				echo -e "\x1b[1;31m ERROR:\x1b[0m No es un rango de IP valido."
				read -p "*Rango de IP para los clientes: [10.0.0.5 10.0.0.50] " ramgo_ip
			done
			read -p "Mascara para los clientes: [255.255.255.0] " masc
			#MIRAR SI LO QUE PUSO ES UNA MASCARA
			if [[ $masc != "" ]]; then
				masc=$(comprobar_ip "Mascara para los clientes: [255.255.255.0] " "$masc")
			fi
			read -p "DNS para los clientes: [8.8.8.8, 8.8.4.4] " dns
			read -p "Nombre del dominio DNS para los clientes: [ejemplo.es] " nombre_dominio_dns
			read -p "Puerta de enlace para los clientes: [10.0.0.1] " router
			#SI METIO ALGO LO COMPROBAMOS
			if [[ $router != "" ]]; then
				router=$(comprobar_ip "Puerta de enlace para los clientes: [10.0.0.1] " "$router")
			fi
			read -p "Broadcast para los clientes: [10.0.0.255] " broadcast
			#SI METIO ALGO LO COMPROBAMOS
			if [[ $broadcast != "" ]]; then
				broadcast=$(comprobar_ip "Broadcast para los clientes: [10.0.0.255] " "$broadcast")
			fi

			#MIRAMOS SI INTRODUJO ALGUN CAMPO OPCIONAL
			if [[ $masc != "" ]]; then
				masc="option subnet-mask $masc;"
			fi
			if [[ $dns != "" ]]; then
				dns="option domain-name-servers $dns;"
			fi
			if [[ $nombre_dominio_dns != "" ]]; then
				nombre_dominio_dns="option domain-name \"$nombre_dominio_dns\";"
			fi
			if [[ $router != "" ]]; then
				router="option routers $router;"
			fi
			if [[ $broadcast != "" ]]; then
				broadcast="option routers $broadcast;"
			fi

			echo -e "
default-lease-time $tiempo_concesion;
max-lease-time $tiempo_maximo_concesion;
ddns-update-style none;

authoritative;

subnet $subnet netmask $masc_subnet {
  range $ramgo_ip;
  $masc
  $dns
  $nombre_dominio_dns
  $router
  $broadcast

  #IP RESERVADAS


  #FIN IP RESERVADAS
}

#LIMITAR USO DEL DHCP


#FIN LIMITAR USO DEL DHCP
			" > /etc/dhcp/dhcpd.conf

			#ESPECIFICAMOS LA TARJETA DE RED QUE TENDRA EL DHCP
			ip a
			read -p "Que interfaz de red estara escuchando el dhcp? [eth0 eth1] " interfaz_red

			#LA INTERFAZ NO PUEDE ESTAR VACIA
			while [ "$interfaz_red" == "" ]
			do
				echo -e "\x1b[1;31m ERROR:\x1b[0m La interfaz de red no puede estar vacia."
				read -p "Que interfaz de red estara escuchando el dhcp? [eth0 eth1] " interfaz_red
			done

			comprobar_interfaz "$interfaz_red"

			#REALIZAMOS UNA COPIA DE LA CONFIGURACION QUE TIENE POR DEFECTO
			if [[ `cat /etc/default/isc-dhcp-server | grep '# Defaults for isc-dhcp-server'` != "" ]]
			then
			        echo "SE REALIZARA UNA COPIA DEL ARCHIVO /etc/default/isc-dhcp-server EN EL MISMO SITIO."
			        cp /etc/default/isc-dhcp-server /etc/default/isc-dhcp-server.back
			fi

			echo -e "
#ESTA SERA LA INTERFAZ DE RED QUE ESCUCHARA EL DHCP
INTERFACESv4=\"$interfaz_red\"
INTERFACESv6=\"\"
			" > /etc/default/isc-dhcp-server

			#REINICIAMOS EL DHCP
			service isc-dhcp-server stop
			service isc-dhcp-server start

			#MIRAMOS SI EL SERVIDOR ESTA FUNCIONANDO
			if [[ `netstat -punta | grep dhcp` == "" ]]
			then
				echo -e "\x1b[1;31m ERROR:\x1b[0m El servidor no puedo iniciar, verifique que esta todo correcto con el comando \"dhcpd -t -cf /etc/dhcp/dhcpd.conf\""
				exit 1
			fi

			echo -e "SERVIDOR PUESTO EN MARCHA [\x1b[1;32m OK \x1b[0m]"
			read -p "Pulsa intro para ir al menu"
		;;
		#RESERVAR IP
		3)
			clear
			echo "----------------------------------------------"
                        echo "                 IP RESERVADA                 "
                        echo "----------------------------------------------"

			#LISTAMOS LOS ORDENADORES YA CONECTADO POR DHCP POR SI QUEREMOS PONER UNO QUE ESTA CONECTADO
			dhcp-lease-list --lease

			echo ""
			read -p "*Nombre del host: " nombre
			read -p "*MAC del equipo para asociarla: " mac
			#LE PEDIMOS LA IP Y LA COMPROBAMOS
			ip=$(comprobar_ip "*IP que quieres asociar al equipo: " "$ip")

			#COMPROBAMOS QUE RELLENO TODOS LOS CAMPOS
                        comprobar_campos_vacios "$nombre" "$mac" "$ip"

			sed -i "s/  #IP RESERVADAS/  #IP RESERVADAS\n    host $nombre {\n      hardware ethernet $mac;\n      fixed-address $ip;\n    }/" /etc/dhcp/dhcpd.conf

			#SI SALE TODO CORRECTO
			if [[ $? == 0 ]]
			then
				echo "Reserva añadida, procedemos al reinicio del DHCP."
				service isc-dhcp-server stop
	                        service isc-dhcp-server start

				#MIRAMOS SI EL SERVIDOR ESTA FUNCIONANDO
                        	if [[ `netstat -punta | grep dhcp` == "" ]]
                        	then
                                	echo -e "\x1b[1;31m ERROR:\x1b[0m El servidor no puedo iniciar, verifique que esta todo correcto con el comando \"dhcpd -t -cf /etc/dhcp/dhcpd.conf\""
                                	exit 1
                        	fi

				echo -e "El servidor de DHCP ya esta listo y en funcionamiento [\x1b[1;32m OK \x1b[0m]"
				echo -e "\x1b[1;36m NOTA:\x1b[0m Para efectuar los cambios el cliente tendra que reiniciar la tarjeta de red o esperar el tiempo de alquiler."
				echo "      Si al equipo se le asigno una IP, la IP estara en reserva hasta que transcurra el tiempo de alquiler."
				read -p "Pulsa intro para ir al menu"
			else
				echo -e "\x1b[1;31m ERROR:\x1b[0m No se pudo añadir la reserva al archivo /etc/dhcp/dhcpd.conf"
				exit 1
			fi
		;;
		#ELIMINAR RESERVA
		4)
			clear
                        echo "----------------------------------------------"
                        echo "             ELIMINAR RESERVADA               "
                        echo "----------------------------------------------"

			#MOSTRAMOS LAS IP RESERVADAS
			ip_reservada

			read -p "MAC del ordenador con la reserva: " mac

			#BUSCAMOS EL NUMERO DE LINIA INICIO Y FIN DE LA MAC, LE RESTAMOS Y LE SUMAMOS HASTA DAR CON EL INICIO Y FIN
			primer_linea=`expr $(cat /etc/dhcp/dhcpd.conf | grep -n "$mac" | cut -d ':' -f 1) - 1`
			ultima_linea=`expr $(cat /etc/dhcp/dhcpd.conf | grep -n "$mac" | cut -d ':' -f 1) + 2`"p"
			ultima_linea_para_eliminar=`expr $(cat /etc/dhcp/dhcpd.conf | grep -n "$mac" | cut -d ':' -f 1) + 2`

			echo "--------------------------------------------"
			sed -n "$primer_linea,$ultima_linea" /etc/dhcp/dhcpd.conf
			echo "--------------------------------------------"

			echo "El contenido de arriba sera el que se eliminara del archivo"
			read -p "¿Quieres eliminarlo? [y/N] " permi

			if [[ $permi == "Y" || $permi == "y" ]]
			then
				echo "Procedemos a la eliminacion."
				#ELIMINAMOS EL RANGO DE LINEA
				sed "$primer_linea,$ultima_linea_para_eliminar d" /etc/dhcp/dhcpd.conf > /etc/dhcp/dhcpd.conf.tmp

				#SI FUNCIONO EL COMANDO ANTERIOR
				if [[ $? == 0 ]]
				then
					#NO DEJA AÑADIRLO DIRECTAMENTE, PROCEDO A CREAR UN ARCHIVO TEMPORAR Y CAMBIARLE EL NOMBRE
					# PARA EFECTUAR LOS CAMBIOS CORRESPONDIENTES
					rm /etc/dhcp/dhcpd.conf
					mv /etc/dhcp/dhcpd.conf.tmp /etc/dhcp/dhcpd.conf

					echo -e "Direccion IP reservada, fue eliminada [\x1b[1;32m OK \x1b[0m]"
					echo "Procedemos al reinicio del servidor."

					service isc-dhcp-server stop
	                                service isc-dhcp-server start

					echo -e "Servidor DHCP reiniciado [\x1b[1;32m OK \x1b[0m]"
				else
					echo -e "\x1b[1;31m ERROR:\x1b[0m Eliminar la reserva."
				fi

				read -p "Pulsa intro para ir al menu"
			else
				echo "NO SE ELIMINO NADA DEL ARCHIVO"
				read -p "Pulsa intro para ir al menu"
			fi
		;;
		#LISTAR LAS MAQUINAS
		5)
			dhcp-lease-list --lease
			echo -e "\x1b[1;36m NOTA:\x1b[0m Las direcciones reservadas no apareceran en el listado."
			read -p "Pulsa intro para ir al menu"
		;;
		#LISTAR IP RESERVADAS
		6)
			ip_reservada
                        read -p "Pulsa intro para ir al menu"
		;;
		#ON/OFF LIMITAR USO DHCP
		7)
			echo ""
			echo "SI ACTIVA EL LIMITE DE USO DHCP, SOLO LOS EQUIPOS CON LA MAC QUE ESPECIFIQUE PODRA USAR EL SERVIDOR DHCP."
			read -p "Apagar o Encender el limite DHCP: [on/OFF] " encender_apagar_limite

			if [[ $encender_apagar_limite == "on" || $encender_apagar_limite == "ON" || $encender_apagar_limite == "On" ]]
			then
				#LE AÑADIMOS EL PARAMETRO deny unknown-clients; PARA RESTRINGIR EL USO DEL DHCP
				sed -i "s/#LIMITAR USO DEL DHCP/deny unknown-clients;\n#LIMITAR USO DEL DHCP/" /etc/dhcp/dhcpd.conf
				echo "LIMITE DE USO DHCP ESTA ENCENDIDO"
				read -p "Pulsa intro para ir al menu"
			else
				#SE LO QUITAMOS PARA QUE TODO LOS ORDENADORES PUEDAN USAR EL DHCP
				sed -i "s/deny unknown-clients;/ /" /etc/dhcp/dhcpd.conf
				echo "LIMITE DE USO DHCP ESTA APAGADO"
				read -p "Pulsa intro para ir al menu"
			fi

			#REINICIAMOS EL SERVIDOR PARA EFECTUAR LAS MODIFICACIONES
			service isc-dhcp-server restart

		;;
		#LIMITAR EL USO DEL SERVIDOR DHCP
		8)
			clear
			echo "----------------------------------------------"
                        echo "            LIMITE DE USO DEL DHCP            "
                        echo "             -  AÑADIR EQUIPO -               "
                        echo "----------------------------------------------"

			dhcp-lease-list --lease

			echo ""
			echo "NOTA: Limitamos el uso del servidor DHCP para que solo lo pueda utilizar las pesonas que añadimos."
			read -p "*Nombre del host: [impresora] " nombre
			read -p "*MAC de equipo: " mac

			#COMPROBAMOS QUE RELLENO TODOS LOS CAMPOS
                        comprobar_campos_vacios "$nombre" "$mac"

			#AÑADIMOS LA MAC PARA QUE PUEDA USAR EL DHCP
			sed -i "s/#LIMITAR USO DEL DHCP/#LIMITAR USO DEL DHCP\nhost $nombre {\n  hardware ethernet $mac;\n}/" /etc/dhcp/dhcpd.conf

			echo "SE A AÑADIDO LOS SIGUIENTES DATOS"
			echo "Host: $nombre MAC: $mac"

			#REINICIAMOS EL SERVIDOR PARA EFECTUAR LAS MODIFICACIONES
			service isc-dhcp-server restart

			read -p "Pulsa intro para ir al menu"
		;;
		#ELIMINAR EQUIPO
		9)
			clear
			echo "----------------------------------------------"
                        echo "            LIMITE DE USO DEL DHCP            "
			echo "             - ELIMINAR EQUIPO -              "
                        echo "----------------------------------------------"

			

		;;
		#EN EL CASO DE QUE NO PONGA NADA QUE RECARGE EL MENU
		*)
			read -p "Orden no encontrada."
		;;
	esac
done


